name: Build website

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
    - name: Update Visual Studio Latest Release
      shell: bash
      run: |
        dotnet tool update -g dotnet-vs
        echo "-- About RELEASE --"
        vs where release
        echo "-- Update RELEASE --"
        vs update release Enterprise
        vs modify release Enterprise +mobile +desktop +uwp +web
        echo "-- RELEASE Updated --"
        vs where release

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
        repository: glennawatson/Docable5
        path: theme

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
          7.0.x

        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-prerelease: true

    - name: Install DotNet workloads
      shell: bash
      run: |
        dotnet workload restore ReactiveUI.Web.sln

    #install android ios tvos macos maui maccatalyst

    - name: Install NuGet 
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '6.x'

    - name: NuGet Restore 
      run: nuget restore

    - name: Build DotNet
      run: dotnet build --no-restore --configuration Release

    - name: Run DotNet
      run: dotnet run -l Debug
    
    #--no-restore --no-build --configuration Release

    - name: Archive output
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: output
        
    - name: Install Node.js
      if: ${{ github.event_name != 'pull_request' }}    
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Deploy netlify   
      if: ${{ github.event_name != 'pull_request' }}    
      run: |
        npm install -g netlify-cli
        netlify deploy --auth=${{ secrets.NETLIFY_DEPLOY_KEY }} --site=${{ secrets.NETLIFY_SITE_ID }} --prod --dir=output
